### ISSUE TITLE
Make it work with OKD

### ISSUE THREAD

**Issue by fabiand** [openshift/assisted-service#2580]
The docs should contain a hint of how AI can be used to deploy OKD instead of OCP

**Comment by mmartinv** [comment]
I tried it my self and I faced the following problems:
* The boot ISO is not correctly generated because the grub file has different paths in RHCOS and FedoraCOS.
* The **next_step_runner** fails to run the inventory command because running podman within podman does not seem to work out of the box in FedoraCOS and the volume '/run/udev' does not exist within the **next_step_runner** container.
* Supporting the CNV/Kubevirt-hyperconverged would need some code changes I believe.
* Currently OCS/Rook is not supported in OKD, there's no operator published in operatorhub and there's not documented way on how to install it.

**Comment by romfreiman** [comment]
The main issue with OKD that the live iso flow wont work - since fedora missing some packages, it actually uses another disk to flush new rootfs. So it will basically will require some redesign. @vrutkovs can provide more details here.

Another gap is that our auth is based on PS - and this will have to be adjusted.

**Comment by vrutkovs** [comment]
https://github.com/openshift/installer/pull/5463 should fix two disk requirement. It leaves `BootstrapInPlace.InstallationDisk` setting unused (this is the disk where bootstrap node needs to be written)
